INDEXING PANDAS TIME SERIES

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("pokemon.csv")

In [3]:
data.head()

#           Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  \
0  1      Bulbasaur  Grass  Poison  45      49       49       65       65   
1  2        Ivysaur  Grass  Poison  60      62       63       80       80   
2  3       Venusaur  Grass  Poison  80      82       83      100      100   
3  4  Mega Venusaur  Grass  Poison  80     100      123      122      120   
4  5     Charmander   Fire     NaN  39      52       43       60       50   

   Speed  Generation  Legendary  
0     45           1      False  
1     60           1      False  
2     80           1      False  
3     80           1      False  
4     65           1      False

Yukarıda görüldüğü üzere, indeks değerleri 0,1,2,3,4 şeklindedir. Pandas Time Serie'lerin özellikleri, indekslerin time serie'lerden oluşmasıdır. 

int, float, str gibi veri tiplerimiz olduğunu hatırlayalım. Bir başka veri tipi ise, 'datetime' dır. datetime = object 'dir.

parse_dates(boolean) şeklinde bir metod vardır. Bu metod yyyy-mm-dd formatındaki stringi yyyy-mm-dd hh:mm:ss dormatına çevirir.

In [4]:
time_list = ["1992-03-08","1992-04-12"]
print(type(time_list[1])) 
datetime_object = pd.to_datetime(time_list)
print(type(datetime_object))

<class 'str'>
<class 'pandas.core.indexes.datetimes.DatetimeIndex'>


İki adet string tutan time_list isimli bir liste oluşturduk. Bu listenin 1.indeksindeki değerin tipinin string olduğunu çıktıda görüyoruz. 

Sonrasında listeyi pd.to_datetime ile datetime tipine dönüştürüyoruz. Ve çıktıda dönüşüm sonucunu görüyoruz.

In [5]:
import warnings
warnings.filterwarnings("ignore")
#Yukarıda yaptığım şey, anlamını çözemediğim bir hatayı kapatmaktır.

data2 = data.head()
date_list = ["1992-01-10","1992-02-10","1992-03-10","1993-03-15","1993-03-16"]
datetime_object = pd.to_datetime(date_list)
data2["date"] = datetime_object

data2= data2.set_index("date")
data2 

#           Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
date                                                                        
1992-01-10  1      Bulbasaur  Grass  Poison  45      49       49       65   
1992-02-10  2        Ivysaur  Grass  Poison  60      62       63       80   
1992-03-10  3       Venusaur  Grass  Poison  80      82       83      100   
1993-03-15  4  Mega Venusaur  Grass  Poison  80     100      123      122   
1993-03-16  5     Charmander   Fire     NaN  39      52       43       60   

            Sp. Def  Speed  Generation  Legendary  
date                                               
1992-01-10       65     45           1      False  
1992-02-10       80     60           1      False  
1992-03-10      100     80           1      False  
1993-03-15      120     80           1      False  
1993-03-16       50     65           1      False

Pokemon datamıza time serisi ile ilgili yapabileceğimiz bir zaman indeksi ya da zaman feature'si olmadığı için onun ilk 5 sample'ına bir time listesi ekledik.

Sonra bu time listesini pandas'ın to_datetime() metodu ile datatime objesine çevirdik ve data'mıza sütun ismi date olacak şekilde bu objeyi ekledik.

Hatırlarsanız indeksler 0,1,2,3,4 şeklindeydi ve burada set_index() metodu ile indekslerin date sütunundaki değerler olmasını sağladık. Böylece artık indeksler datetime objesidir. Yani data'mız artık bir time series data'dır.

Time series data, zamana bağlı data demektir.

Şimdi Time series data'mız ile yapabileceklerimizi görelim.

In [6]:
print(data2.loc["1993-03-16"])
print(data2.loc["1992-03-10":"1993-03-16"])

#                      5
Name          Charmander
Type 1              Fire
Type 2               NaN
HP                    39
Attack                52
Defense               43
Sp. Atk               60
Sp. Def               50
Speed                 65
Generation             1
Legendary          False
Name: 1993-03-16 00:00:00, dtype: object
            #           Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
date                                                                        
1992-03-10  3       Venusaur  Grass  Poison  80      82       83      100   
1993-03-15  4  Mega Venusaur  Grass  Poison  80     100      123      122   
1993-03-16  5     Charmander   Fire     NaN  39      52       43       60   

            Sp. Def  Speed  Generation  Legendary  
date                                               
1992-03-10      100     80           1      False  
1993-03-15      120     80           1      False  
1993-03-16       50     65           1      False  


loc ifadesi data'nın içinden belli bir indeksteki şeyleri çekmemizi sağlar. ama bizim indeksimiz artık time serisi olduğu için biz buna istediğimiz tarihi yazıp print ettirebiliyoruz.

Çıktıda görüldüğü üzere, indeksi 1993-03-16 olan satırın bilgilerini yazdırdık.

Birde iki time series arasını yazdırabilmemiz de mümkün. Burada 1992-03-10 ile 1993-03-16 indekleri arasındaki satırları yazdırdık.

RESAMPLING PANDAS TIME SERIES

Resampling: Bir data'nın içerisinden elde ettiğimiz yeni sample'lere denir.

Time series objesinin kullanışlı metodları vardır. Mesela "M" harfini kullanarak tüm ayları, istediğimiz ayları resample edebiliriz. Ya da "A" harfini kullanarak tüm yılları, istediğimiz yılları resample edebiliriz.

Mesela yılları resample etmek istiyoruz ve yılların ortalama hız değerlerini bulmak istiyoruz. 1992 yılından 3 tane time serisinden sample var. 1993 ten de 2 tane var. Hızı (Speed) bulmak için, yıla göre resample yaparız ve bunun hızının ortalamasını buluruz. Bunu time series ile yapmak çok kolay çünkü onun için özel metodlar var. Maksimumu, standart sapması gibi istatistiksel bilgileri kolaylıkla elde edebilmemiz mümkün.

In [7]:
data2.resample("A").mean()

#         HP     Attack  Defense    Sp. Atk    Sp. Def  \
date                                                                   
1992-12-31  2.0  61.666667  64.333333     65.0  81.666667  81.666667   
1993-12-31  4.5  59.500000  76.000000     83.0  91.000000  85.000000   

                Speed  Generation  Legendary  
date                                          
1992-12-31  61.666667         1.0        0.0  
1993-12-31  72.500000         1.0        0.0

data2'yi yıla (A) göre resample ettik. data2'de 1992 ve 1993 şeklinde 2 farklı yıl var. Yani data2'yi yıla göre resample ettiğimizde sonuç olarak 2 tane yıl elde edicez. Resample et ve mean() metodundan dolayı ortalamasını al demiş olduk.

Böylece tüm yıllara göre resample edip, o yılların tüm değerlerinin ortalamasını aldık. 

Çıktıyı inceleyelim. 1992 yılındaki pokemonların can (HP) ortalaması 61.6 ymış. Bunun anlamı, 1992 yılında 3 tane pokemon var ve data2'de görebileceğiniz üzere bunların can (HP) değerleri sırasıyla 45,60,80 dir. (45+60+80)/3=61,6 elde edilir.

In [8]:
data2.resample("M").mean()

#    HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Generation  \
date                                                                          
1992-01-31  1.0  45.0    49.0     49.0     65.0     65.0   45.0         1.0   
1992-02-29  2.0  60.0    62.0     63.0     80.0     80.0   60.0         1.0   
1992-03-31  3.0  80.0    82.0     83.0    100.0    100.0   80.0         1.0   
1992-04-30  NaN   NaN     NaN      NaN      NaN      NaN    NaN         NaN   
1992-05-31  NaN   NaN     NaN      NaN      NaN      NaN    NaN         NaN   
1992-06-30  NaN   NaN     NaN      NaN      NaN      NaN    NaN         NaN   
1992-07-31  NaN   NaN     NaN      NaN      NaN      NaN    NaN         NaN   
1992-08-31  NaN   NaN     NaN      NaN      NaN      NaN    NaN         NaN   
1992-09-30  NaN   NaN     NaN      NaN      NaN      NaN    NaN         NaN   
1992-10-31  NaN   NaN     NaN      NaN      NaN      NaN    NaN         NaN   
1992-11-30  NaN   NaN     NaN      NaN      NaN      NaN    NaN         NaN   
1992-12-31  NaN   NaN     NaN      NaN      NaN      NaN    NaN         NaN   
1993-01-31  NaN   NaN     NaN      NaN      NaN      NaN    NaN         NaN   
1993-02-28  NaN   NaN     NaN      NaN      NaN      NaN    NaN         NaN   
1993-03-31  4.5  59.5    76.0     83.0     91.0     85.0   72.5         1.0   

            Legendary  
date                   
1992-01-31        0.0  
1992-02-29        0.0  
1992-03-31        0.0  
1992-04-30        NaN  
1992-05-31        NaN  
1992-06-30        NaN  
1992-07-31        NaN  
1992-08-31        NaN  
1992-09-30        NaN  
1992-10-31        NaN  
1992-11-30        NaN  
1992-12-31        NaN  
1993-01-31        NaN  
1993-02-28        NaN  
1993-03-31        0.0

Aylara göre resample ettik. Bir yılda 12 ay olduğunu biliyoruz ve 1992 yılına baktığımızda 1. , 2. ve 3. aylar için resamble yaptık. Fakat 4.aya geçtiğimizde data'da 4.aydan sonrası olmadığı için bunlara NaN value'si atanıyor.

Ayrıca dikkatinizi çekerim ki, 1992 yılının 1. ayındaki değerlere baktığımızda data2'deki değerler ile aynı. Bunun sebebi, 1992 yılının 1.ayına ait tek bir satır olmasıdır. 

1993 yılının 3.ayına ait 2 adet satır var ve aylara göre resample yaptığımızda bu 2 satırın ortalamaları buradaki çıktıya yansıtılır. 

1993 yılının 4.ayına NaN yazmama sebebi, bu metodda en erken yıl (1992) ile en geç yıl (1993) arasını aylara göre doldurur.

In [9]:
data2.resample("M").first().interpolate("linear")

#           Name Type 1  Type 2    HP  Attack     Defense  \
date                                                                           
1992-01-31  1.000000      Bulbasaur  Grass  Poison  45.0    49.0   49.000000   
1992-02-29  2.000000        Ivysaur  Grass  Poison  60.0    62.0   63.000000   
1992-03-31  3.000000       Venusaur  Grass  Poison  80.0    82.0   83.000000   
1992-04-30  3.083333           None   None    None  80.0    83.5   86.333333   
1992-05-31  3.166667           None   None    None  80.0    85.0   89.666667   
1992-06-30  3.250000           None   None    None  80.0    86.5   93.000000   
1992-07-31  3.333333           None   None    None  80.0    88.0   96.333333   
1992-08-31  3.416667           None   None    None  80.0    89.5   99.666667   
1992-09-30  3.500000           None   None    None  80.0    91.0  103.000000   
1992-10-31  3.583333           None   None    None  80.0    92.5  106.333333   
1992-11-30  3.666667           None   None    None  80.0    94.0  109.666667   
1992-12-31  3.750000           None   None    None  80.0    95.5  113.000000   
1993-01-31  3.833333           None   None    None  80.0    97.0  116.333333   
1993-02-28  3.916667           None   None    None  80.0    98.5  119.666667   
1993-03-31  4.000000  Mega Venusaur  Grass  Poison  80.0   100.0  123.000000   

               Sp. Atk     Sp. Def  Speed  Generation  Legendary  
date                                                              
1992-01-31   65.000000   65.000000   45.0         1.0        0.0  
1992-02-29   80.000000   80.000000   60.0         1.0        0.0  
1992-03-31  100.000000  100.000000   80.0         1.0        0.0  
1992-04-30  101.833333  101.666667   80.0         1.0        0.0  
1992-05-31  103.666667  103.333333   80.0         1.0        0.0  
1992-06-30  105.500000  105.000000   80.0         1.0        0.0  
1992-07-31  107.333333  106.666667   80.0         1.0        0.0  
1992-08-31  109.166667  108.333333   80.0         1.0        0.0  
1992-09-30  111.000000  110.000000   80.0         1.0        0.0  
1992-10-31  112.833333  111.666667   80.0         1.0        0.0  
1992-11-30  114.666667  113.333333   80.0         1.0        0.0  
1992-12-31  116.500000  115.000000   80.0         1.0        0.0  
1993-01-31  118.333333  116.666667   80.0         1.0        0.0  
1993-02-28  120.166667  118.333333   80.0         1.0        0.0  
1993-03-31  122.000000  120.000000   80.0         1.0        0.0

Aylara göre resample edilen data'yı linear bir şekilde interpolate ediyoruz. Bu şu demek:

1,2,3, ,5,6,7

Aradaki boşluğa 4 yazılır. Linear interpolate budur. 

Çıktıda görüldüğü üzere, 1992 yılının 1., 2. ve 3. aylarına sırasıyla 1.000000	, 2.000000, 3.000000 yazmış ve sonrasındaki NaN değerleri 4.000000 'e kadar artan sırada doldurmuş. Yani 3.000000 ile 4.000000 arasında eşit aralıklara bölerek artırmış. 0.08 artırarak doldurmuş.